version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
    environment: 
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_DATABASE}
      NODE_ENV: development
      PORT: 3000
    ports:
      - "${SERVER_PORT:-8090}:3000"
    command: npm run start:dev
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_EXTERNAL_PORT:-35000}:5432'

volumes:
  node-modules:
