version: '3.8'
services:
  api:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    container_name: postgresDB
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
