version: "3.8"
services:
  engine:
    container_name: engine
    build:
      dockerfile: Dockerfile
      context: .
    # env_file:
    #   - .env
    # environment:
    #   HOST: ${HOST}
    #   flaskPORT: ${flaskPORT}
    #   milvusPORT: ${milvusPORT}
    # depends_on:
    #   - milvus
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/src/__pycache__
    ports:
      - 5000:5000

  # milvus:
  #   container_name: milvus
  #   image: milvusdb/milvus
  #   ports:
  #     - 19530:19530
# docker network create elastic
# networks:
#   elastic:
#     driver: bridge
#     external: true
#     internal: true
